#ifndef _EVENT_H_
#define _EVENT_H_

#include<QEvent>
#include"global.h"

namespace qt_elevencent{

  enum EVENT_TYPE{
    EVENT_TYPE_START=QEvent::Type(QEvent::User),

    EVENT_TYPE_APP_RUN,
    EVENT_TYPE_HOME_VIEW_SHOW,
    EVENT_TYPE_ON_HOME_MSG_VIEW_SHOW,
    EVENT_TYPE_ON_HOME_MSG_VIEW_CREATE,    
    EVENT_TYPE_DEBUG_VIEW_SHOW,
    EVENT_TYPE_DEBUG_VIEW_HIDE,
    EVENT_TYPE_CMD_VIEW_SHOW,
    EVENT_TYPE_CMD_VIEW_HIDE,
    EVENT_TYPE_CMD_VIEW_HINT_MSG,
    EVENT_TYPE_CMD_VIEW_OUTPUT,
    EVENT_TYPE_CMD_MAIN,
    EVENT_TYPE_CMD_LINE,    
    EVENT_TYPE_NET_REQ_PUBKEY,
    EVENT_TYPE_NET_TX,
    EVENT_TYPE_NET_ON_CONNECTED,
    EVENT_TYPE_NET_ON_AUTO_RELOGIN,
    EVENT_TYPE_NET_ON_DISCONNECTED,
    EVENT_TYPE_NET_ON_LOGIN_SUCCESS,
    EVENT_TYPE_NET_ON_NEW_LOGIN_SUCCESS,        
    EVENT_TYPE_TOAST_SHOW,
    EVENT_TYPE_GET_CONNED_SERVER,
    EVENT_TYPE_GET_CONNED_SERVER_POINTER,    
    EVENT_TYPE_RESP_MSG_USERS,
    EVENT_TYPE_RESP_USER_REQ_MSG,
    
    EVENT_TYPE_MAX
  };
  class AppEvent:public QEvent{
  public:
    void*data;
    AppEvent(EVENT_TYPE type,void*pdata=0):QEvent(QEvent::Type(type)),data(pdata){}
  };
  
}


#endif
