# This file is managed by Qt Creator, do not edit!

set("CMAKE_GENERATOR" "Ninja" CACHE "STRING" "" FORCE)
set("CMAKE_BUILD_TYPE" "Debug" CACHE "STRING" "" FORCE)
set("CMAKE_PROJECT_INCLUDE_BEFORE" "/dc/remote_mapper/susu1970/node2x/dynamic/app/linux/Qt/Tools/QtCreator/share/qtcreator/package-manager/auto-setup.cmake" CACHE "FILEPATH" "" FORCE)
set("QT_QMAKE_EXECUTABLE" "/dc/remote_mapper/susu1970/node2x/dynamic/app/linux/Qt/6.2.4/android_armv7/bin/qmake" CACHE "FILEPATH" "" FORCE)
set("CMAKE_PREFIX_PATH" "/dc/remote_mapper/susu1970/node2x/dynamic/app/linux/Qt/6.2.4/android_armv7" CACHE "PATH" "" FORCE)
set("CMAKE_C_COMPILER" "/dc/remote/susu1970/node2x/dynamic/app/linux/android-sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" CACHE "FILEPATH" "" FORCE)
set("CMAKE_CXX_COMPILER" "/dc/remote/susu1970/node2x/dynamic/app/linux/android-sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" CACHE "FILEPATH" "" FORCE)
set("ANDROID_NATIVE_API_LEVEL" "23" CACHE "STRING" "" FORCE)
set("ANDROID_NDK" "/dc/remote/susu1970/node2x/dynamic/app/linux/android-sdk/ndk/22.1.7171670" CACHE "PATH" "" FORCE)
set("CMAKE_TOOLCHAIN_FILE" "/dc/remote/susu1970/node2x/dynamic/app/linux/android-sdk/ndk/22.1.7171670/build/cmake/android.toolchain.cmake" CACHE "FILEPATH" "" FORCE)
set("ANDROID_ABI" "armeabi-v7a" CACHE "STRING" "" FORCE)
set("ANDROID_STL" "c++_shared" CACHE "STRING" "" FORCE)
set("CMAKE_FIND_ROOT_PATH" "/dc/remote_mapper/susu1970/node2x/dynamic/app/linux/Qt/6.2.4/android_armv7" CACHE "PATH" "" FORCE)
set("QT_NO_GLOBAL_APK_TARGET_PART_OF_ALL" "ON" CACHE "BOOL" "" FORCE)
set("QT_HOST_PATH" "/dc/remote_mapper/susu1970/node2x/dynamic/app/linux/Qt/6.2.4/gcc_64" CACHE "PATH" "" FORCE)
set("ANDROID_SDK_ROOT" "/dc/remote_mapper/susu1970/node2x/dynamic/app/linux/android-sdk" CACHE "PATH" "" FORCE)